name: build iOS

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: '${{ secrets.WEST_REPOSITORY_OWNER }}/nts-west-native-ios'
          ref: ${{ github.head_ref }}
          token: ${{ secrets.WEST_CHECKOUT_TOKEN }}
      - name: Hello world
        run: |
          echo "Hello world"
          ls -lia
